name: 'ROS 2 Build Debian Package'
description: 'Build Debian packages from a ROS 2 project'
author: 'ICHIRO ITS'
branding:
  icon: 'package'
  color: 'gray-dark'
inputs:
  ros2-distro:
    description: 'The ROS 2 distribution to be used.'
    required: false
    default: 'foxy'
runs:
  using: 'composite'
  steps:
    - run: echo 'using ROS 2 ${{ inputs.ros2-distro }}.'
      shell: bash
