name: Action Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  action-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        ros2-distro: [foxy, rolling]
    steps:
      - name: Test the action
        uses: ./
        with:
          ros2-distro: ${{ matrix.ros2-distro }}
