name: Action Test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  action-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            ros2-distro: foxy
          - os: ubuntu-20.04
            ros2-distro: galactic
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4

      - name: Checkout ROS 2 examples
        uses: actions/checkout@v2.3.4
        with:
          repository: ros2/examples
          fetch-depth: 0
          path: examples

      - name: Checkout ROS 2 examples on non master branch
        if: ${{ matrix.ros2-distro != 'rolling' }}
        run: git checkout ${{ matrix.ros2-distro }}
        working-directory: examples

      - name: Only test some packages
        run: |
          mv examples/rclcpp/topics cpptopics || true
          mv examples/rclcpp/minimal_publisher . || true
          mv examples/rclcpp/minimal_subscriber . || true
          mv examples/rclpy/topics pytopics || true
          rm -rf examples test || true

      - name: Test the action
        uses: ./
        with:
          ros2-distro: ${{ matrix.ros2-distro }}

      - name: Upload build result
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Package
          path: package

  action-test-failure:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        package: [failed_build]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4

      - name: Only test some packages
        run: |
          mv test/${{ matrix.package }} ${{ matrix.package }} || true
          rm -rf test || true

      - name: Test the action
        id: failedstep
        continue-on-error: true
        uses: ./

      - name: Fails if previous step has succeeded
        if: ${{ steps.failedstep.outcome == 'success' }}
        run: false

  action-test-with-output-dir:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4

      - name: Checkout ROS 2 examples on foxy branch
        uses: actions/checkout@v2.3.4
        with:
          repository: ros2/examples
          ref: foxy
          path: examples

      - name: Only test some packages
        run: |
          mv examples/rclcpp/topics cpptopics || true
          mv examples/rclpy/topics pytopics || true
          rm -rf examples test || true

      - name: Test the action with output directory
        uses: ./
        with:
          ros2-distro: foxy
          output-dir: output

      - name: Test output directory
        run: test $(ls -1 output | wc -l) -eq 6

  action-test-with-unique-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4

      - name: Checkout ROS 2 examples on foxy branch
        uses: actions/checkout@v2.3.4
        with:
          repository: ros2/examples
          ref: foxy
          path: examples

      - name: Only test some packages
        run: |
          mv examples/rclcpp/topics cpptopics || true
          mv examples/rclpy/topics pytopics || true
          rm -rf examples test || true

      - name: Test the action with unique version
        uses: ./
        with:
          ros2-distro: foxy
          unique-version: true

      - name: Test unique version
        run: |
          (for PACKAGE in $(ls)
          do
            test "$(dpkg -f $PACKAGE Version)" != '0.9.4-0focal' || exit $?
          done)
        working-directory: package
